#!/bin/bash

# This script creates localization files for Sparky CA.

# Function to create a language file
create_lang_file() {
    lang_code=$1
    local1=$2
    local2=$3
    local3=$4
    local4=$5
    local5=$6
    local11=$7
    local12=$8
    local13=$9
    local14=${10}
    local15=${11}
    local_must_be_root=${12}
    local_sparky_xterm_missing=${13}
    local_all_certificates=${14}

    cat > lang/$lang_code <<EOF
# $lang_code localization file for Sparky CA.
# Copyright 2018 Paweł "pavroo" Pijanowski <pavroo@onet.eu>
# Copyright 2025 Jules <jules@smol.ai>
# Under the GNU GPL v2
# Last update 2025/11/19
LOCAL1="$local1"
LOCAL2="$local2"
LOCAL3="$local3"
LOCAL4="$local4"
LOCAL5="$local5"
LOCAL11="$local11"
LOCAL12="$local12"
LOCAL13="$local13"
LOCAL14="$local14"
LOCAL15="$local15"
LOCAL_MUST_BE_ROOT="$local_must_be_root"
LOCAL_SPARKY_XTERM_MISSING="$local_sparky_xterm_missing"
LOCAL_ALL_CERTIFICATES="$local_all_certificates"
### .desktop file to be translated too
# Name[$lang_code]=PJeOffice CA Certificates Installer
# Comment[$lang_code]=PJeOffice CA Certificates Installer
EOF
}

create_lang_file "ast" "Nome" "Descripción" "Salir" "Instalador de certificaos" "Instala certificaos de CA dientro del to sistema operativu. \n\nPor favor, escueyi una opción" "el certificáu yá esiste." "¿Tengo de volver a descargalo?" "Sí" "Non" "Descargáronse ya instalaron los siguientes certificaos:" "Tien de ser root... Saliendo..." "falta sparky-xterm... Saliendo..." "Tolos certificaos raíz d'ICP-Brasil"
create_lang_file "be" "Імя" "Апісанне" "Выхад" "Усталёўшчык сертыфікатаў" "Усталёўвае сертыфікаты CA ў вашай аперацыйнай сістэме. \n\nКалі ласка, абярыце опцыю" "сертыфікат ужо існуе." "Ці варта мне яго паўторна загрузіць?" "Так" "Не" "Наступныя сертыфікаты былі загружаныя і ўсталяваныя:" "Павінен быць root... Выхад..." "адсутнічае sparky-xterm... Выхад..." "Усе каранёвыя сертыфікаты ICP-Brasil"
create_lang_file "bg" "Име" "Описание" "Изход" "Инсталатор на сертификати" "Инсталира CA сертификати във вашата операционна система. \n\nМоля, изберете опция" "сертификатът вече съществува." "Трябва ли да го изтегля отново?" "Да" "Не" "Следните сертификати са изтеглени и инсталирани:" "Трябва да сте root... Излизане..." "липсва sparky-xterm... Излизане..." "Всички коренни сертификати на ICP-Brasil"
create_lang_file "bn" "নাম" "বর্ণনা" "প্রস্থান" "সার্টিফিকেট ইনস্টলার" "এটি আপনার অপারেটিং সিস্টেমের ভিতরে CA সার্টিফিকেট ইনস্টল করে। \n\nঅনুগ্রহ করে একটি বিকল্প নির্বাচন করুন" "সার্টিফিকেট ইতিমধ্যে বিদ্যমান।" "আমার কি এটি পুনরায় ডাউনলোড করা উচিত?" "হ্যাঁ" "না" "নিম্নলিখিত সার্টিফিকেটগুলি ডাউনলোড এবং ইনস্টল করা হয়েছে:" "রুট হতে হবে... প্রস্থান করা হচ্ছে..." "sparky-xterm অনুপস্থিত... প্রস্থান করা হচ্ছে..." "সমস্ত ICP-ব্রাজিল রুট সার্টিফিকেট"
create_lang_file "br" "Anv" "Deskrivadur" "Kuitaat" "Staliwr Testennoù" "Staliañ a ra testennoù CA e-barzh ho reizhiad korvoiñ. \n\nDibabit un dibarzh mar plij" "an testenn a zo anezhi c'hoazh." "Ha rankout a ran he adpellgas?" "Ya" "Nann" "An testennoù da-heul a zo bet pellgaset ha staliet:" "Rankout a reer bezañ root... O kuitaat..." "mankout a ra sparky-xterm... O kuitaat..." "An holl testennoù gwrizienn ICP-Brasil"
create_lang_file "bs" "Ime" "Opis" "Izlaz" "Instalater certifikata" "Instalira CA certifikate unutar vašeg operativnog sistema. \n\nMolimo odaberite opciju" "certifikat već postoji." "Da li da ga ponovo preuzmem?" "Da" "Ne" "Sljedeći certifikati su preuzeti i instalirani:" "Mora biti root... Izlazim..." "nedostaje sparky-xterm... Izlazim..." "Svi ICP-Brasil korijenski certifikati"
create_lang_file "ca" "Nom" "Descripció" "Surt" "Instal·lador de certificats" "Instal·la certificats de CA dins del vostre sistema operatiu. \n\nSeleccioneu una opció" "el certificat ja existeix." "L'he de tornar a descarregar?" "Sí" "No" "S'han descarregat i instal·lat els certificats següents:" "Ha de ser root... Sortint..." "falta sparky-xterm... Sortint..." "Tots els certificats arrel d'ICP-Brasil"
create_lang_file "cs" "Název" "Popis" "Konec" "Instalátor certifikátů" "Nainstaluje certifikáty CA do vašeho operačního systému. \n\nVyberte prosím možnost" "certifikát již existuje." "Mám ho stáhnout znovu?" "Ano" "Ne" "Následující certifikáty byly staženy a nainstalovány:" "Musí být root... Ukončuji..." "chybí sparky-xterm... Ukončuji..." "Všechny kořenové certifikáty ICP-Brasil"
create_lang_file "cy" "Enw" "Disgrifiad" "Allan" "Gosodwr Tystysgrifau" "Mae'n gosod tystysgrifau CA y tu mewn i'ch system weithredu. \n\nDewiswch opsiwn" "mae'r dystysgrif eisoes yn bodoli." "A ddylwn i ei ail-lwytho i lawr?" "Ie" "Na" "Mae'r tystysgrifau canlynol wedi'u llwytho i lawr a'u gosod:" "Rhaid bod yn root... Allan..." "mae sparky-xterm ar goll... Allan..." "Holl dystysgrifau gwraidd ICP-Brasil"
create_lang_file "da" "Navn" "Beskrivelse" "Afslut" "Certifikatinstallationsprogram" "Det installerer CA-certifikater i dit operativsystem. \n\nVælg venligst en mulighed" "certifikatet findes allerede." "Skal jeg downloade det igen?" "Ja" "Nej" "Følgende certifikater er blevet downloadet og installeret:" "Skal være root... Afslutter..." "sparky-xterm mangler... Afslutter..." "Alle ICP-Brasil-rodcertifikater"
create_lang_file "de" "Name" "Beschreibung" "Beenden" "Zertifikat-Installer" "Installiert CA-Zertifikate in Ihrem Betriebssystem. \n\nBitte wählen Sie eine Option" "Zertifikat existiert bereits." "Soll ich es erneut herunterladen?" "Ja" "Nein" "Folgende Zertifikate wurden heruntergeladen und installiert:" "Muss Root sein... Beende..." "sparky-xterm fehlt... Beende..." "Alle ICP-Brasil-Stammzertifikate"
create_lang_file "el" "Όνομα" "Περιγραφή" "Έξοδος" "Εγκαταστάτης Πιστοποιητικών" "Εγκαθιστά πιστοποιητικά CA στο λειτουργικό σας σύστημα. \n\nΠαρακαλώ επιλέξτε μια επιλογή" "το πιστοποιητικό υπάρχει ήδη." "Να το κατεβάσω ξανά;" "Ναι" "Όχι" "Τα ακόλουθα πιστοποιητικά έχουν ληφθεί και εγκατασταθεί:" "Πρέπει να είστε root... Έξοδος..." "λείπει το sparky-xterm... Έξοδος..." "Όλα τα ριζικά πιστοποιητικά ICP-Brasil"
create_lang_file "eo" "Nomo" "Priskribo" "Eliri" "Instalilo de Atestiloj" "Ĝi instalas CA-atestilojn en via operaciumo. \n\nBonvolu elekti opcion" "atestilo jam ekzistas." "Ĉu mi elŝutu ĝin denove?" "Jes" "Ne" "La jenaj atestiloj estis elŝutitaj kaj instalitaj:" "Devas esti radiko... Elirante..." "mankas sparky-xterm... Elirante..." "Ĉiuj radikaj atestiloj de ICP-Brasil"
create_lang_file "es" "Nombre" "Descripción" "Salir" "Instalador de certificados" "Instala certificados de CA dentro de su sistema operativo. \n\nPor favor, seleccione una opción" "el certificado ya existe." "¿Debo volver a descargarlo?" "Sí" "No" "Se han descargado e instalado los siguientes certificados:" "Debe ser root... Saliendo..." "falta sparky-xterm... Saliendo..." "Todos los certificados raíz de ICP-Brasil"
create_lang_file "et" "Nimi" "Kirjeldus" "Välju" "Sertifikaadi installija" "See installib CA-sertifikaadid teie operatsioonisüsteemi. \n\nPalun valige suvand" "sertifikaat on juba olemas." "Kas ma peaksin selle uuesti alla laadima?" "Jah" "Ei" "Järgmised sertifikaadid on alla laaditud ja installitud:" "Peab olema juurkasutaja... Väljun..." "sparky-xterm on puudu... Väljun..." "Kõik ICP-Brasili juursertifikaadid"
create_lang_file "eu" "Izena" "Deskribapena" "Irten" "Ziurtagiri-instalatzailea" "CA ziurtagiriak instalatzen ditu zure sistema eragilean. \n\nAukeratu aukera bat" "ziurtagiria lehendik dago." "Berriro deskargatu behar al dut?" "Bai" "Ez" "Ziurtagiri hauek deskargatu eta instalatu dira:" "Errorea izan behar du... Irteten..." "sparky-xterm falta da... Irteten..." "ICP-Brasil erroko ziurtagiri guztiak"
create_lang_file "fa" "نام" "توضیحات" "خروج" "نصب کننده گواهی" "گواهی های CA را در سیستم عامل شما نصب می کند. \n\nلطفا یک گزینه را انتخاب کنید" "گواهی از قبل وجود دارد." "آیا باید دوباره آن را بارگیری کنم؟" "بله" "نه" "گواهی های زیر بارگیری و نصب شده اند:" "باید ریشه باشد... در حال خروج..." "sparky-xterm موجود نیست... در حال خروج..." "همه گواهی های ریشه ICP-Brasil"
create_lang_file "fi" "Nimi" "Kuvaus" "Lopeta" "Varmenteen asennusohjelma" "Se asentaa CA-varmenteet käyttöjärjestelmääsi. \n\nValitse vaihtoehto" "varmenne on jo olemassa." "Pitäisikö minun ladata se uudelleen?" "Kyllä" "Ei" "Seuraavat varmenteet on ladattu ja asennettu:" "Pitää olla root... Poistutaan..." "sparky-xterm puuttuu... Poistutaan..." "Kaikki ICP-Brasil-juurivarmenteet"
create_lang_file "fr" "Nom" "Description" "Quitter" "Installateur de certificats" "Installe les certificats de l'AC dans votre système d'exploitation. \n\nVeuillez sélectionner une option" "le certificat existe déjà." "Dois-je le télécharger à nouveau ?" "Oui" "Non" "Les certificats suivants ont été téléchargés et installés :" "Doit être root... Sortie..." "sparky-xterm est manquant... Sortie..." "Tous les certificats racines d'ICP-Brasil"
create_lang_file "ga" "Ainm" "Cur síos" "Scoir" "Suiteálaí Teastais" "Suiteálann sé teastais CA taobh istigh de do chóras oibriúcháin. \n\nRoghnaigh rogha le do thoil" "tá an teastas ann cheana." "Ar cheart dom é a íoslódáil arís?" "Tá" "Níl" "Tá na teastais seo a leanas íoslódáilte agus suiteáilte:" "Caithfidh a bheith fréamh... Ag fágáil..." "tá sparky-xterm ar iarraidh... Ag fágáil..." "Gach teastas fréimhe ICP-Brasil"
create_lang_file "gl" "Nome" "Descrición" "Saír" "Instalador de certificados" "Instala certificados de CA dentro do seu sistema operativo. \n\nSeleccione unha opción" "o certificado xa existe." "Debo descargalo de novo?" "Si" "Non" "Descargáronse e instaláronse os seguintes certificados:" "Debe ser root... Saíndo..." "falta sparky-xterm... Saíndo..." "Todos os certificados raíz de ICP-Brasil"
create_lang_file "gu" "નામ" "વર્ણન" "બહાર નીકળો" "પ્રમાણપત્ર ઇન્સ્ટોલર" "તે તમારી ઓપરેટિંગ સિસ્ટમમાં CA પ્રમાણપત્રો ઇન્સ્ટોલ કરે છે. \n\nકૃપા કરીને એક વિકલ્પ પસંદ કરો" "પ્રમાણપત્ર પહેલેથી અસ્તિત્વમાં છે." "શું મારે તેને ફરીથી ડાઉનલોડ કરવું જોઈએ?" "હા" "ના" "નીચેના પ્રમાણપત્રો ડાઉનલોડ અને ઇન્સ્ટોલ કરવામાં આવ્યા છે:" "રૂટ હોવું જ જોઈએ... બહાર નીકળી રહ્યું છે..." "sparky-xterm ખૂટે છે... બહાર નીકળી રહ્યું છે..." "બધા ICP-બ્રાઝિલ રુટ પ્રમાણપત્રો"
create_lang_file "he" "שם" "תיאור" "יציאה" "מתקין אישורים" "הוא מתקין אישורי CA במערכת ההפעלה שלך. \n\nאנא בחר אפשרות" "האישור כבר קיים." "האם עלי להוריד אותו מחדש?" "כן" "לא" "האישורים הבאים הורדו והותקנו:" "חייב להיות שורש... יוצא..." "sparky-xterm חסר... יוצא..." "כל אישורי הבסיס של ICP-Brasil"
create_lang_file "hi" "नाम" "विवरण" "बाहर निकलें" "प्रमाणपत्र इंस्टॉलर" "यह आपके ऑपरेटिंग सिस्टम के अंदर CA प्रमाणपत्र स्थापित करता है। \n\nकृपया एक विकल्प चुनें" "प्रमाणपत्र पहले से मौजूद है।" "क्या मुझे इसे फिर से डाउनलोड करना चाहिए?" "हाँ" "नहीं" "निम्नलिखित प्रमाणपत्र डाउनलोड और स्थापित किए गए हैं:" "रूट होना चाहिए... बाहर निकल रहा है..." "sparky-xterm गुम है... बाहर निकल रहा है..." "सभी ICP-ब्राजील रूट प्रमाणपत्र"
create_lang_file "hr" "Ime" "Opis" "Izlaz" "Instalacijski program certifikata" "Instalira CA certifikate unutar vašeg operativnog sustava. \n\nOdaberite opciju" "certifikat već postoji." "Trebam li ga ponovno preuzeti?" "Da" "Ne" "Sljedeći certifikati su preuzeti i instalirani:" "Mora biti root... Izlazim..." "nedostaje sparky-xterm... Izlazim..." "Svi ICP-Brasil korijenski certifikati"
create_lang_file "hu" "Név" "Leírás" "Kilépés" "Tanúsítványtelepítő" "CA-tanúsítványokat telepít az operációs rendszerébe. \n\nKérjük, válasszon egy lehetőséget" "a tanúsítvány már létezik." "Újra le kell töltenem?" "Igen" "Nem" "A következő tanúsítványok lettek letöltve és telepítve:" "Rootnak kell lennie... Kilépés..." "hiányzik a sparky-xterm... Kilépés..." "Az összes ICP-Brasil gyökértanúsítvány"
create_lang_file "hy" "Անուն" "Նկարագրություն" "Ելք" "Հավաստագրի տեղադրիչ" "Այն տեղադրում է CA վկայագրեր ձեր օպերացիոն համակարգում: \n\nԽնդրում ենք ընտրել տարբերակ" "վկայագիրն արդեն գոյություն ունի:" "Արդյո՞ք պետք է այն նորից ներբեռնեմ:" "Այո" "Ոչ" "Ներբեռնվել և տեղադրվել են հետևյալ վկայագրերը." "Պետք է լինի root... Ելք..." "բացակայում է sparky-xterm... Ելք..." "ICP-Brasil-ի բոլոր արմատական վկայագրերը"
create_lang_file "id" "Nama" "Deskripsi" "Keluar" "Pemasang Sertifikat" "Ini memasang sertifikat CA di dalam sistem operasi Anda. \n\nSilakan pilih opsi" "sertifikat sudah ada." "Haruskah saya mengunduhnya kembali?" "Ya" "Tidak" "Sertifikat berikut telah diunduh dan dipasang:" "Harus root... Keluar..." "sparky-xterm hilang... Keluar..." "Semua sertifikat root ICP-Brasil"
create_lang_file "is" "Nafn" "Lýsing" "Hætta" "Skírteinisuppsetningarforrit" "Það setur upp CA-skírteini í stýrikerfinu þínu. \n\nVinsamlegast veldu valkost" "skírteinið er þegar til." "Ætti ég að hlaða því niður aftur?" "Já" "Nei" "Eftirfarandi skírteini hafa verið sótt og sett upp:" "Verður að vera rót... Hættir..." "sparky-xterm vantar... Hættir..." "Öll ICP-Brasil rótarskírteini"
create_lang_file "it" "Nome" "Descrizione" "Esci" "Installatore di certificati" "Installa i certificati CA nel tuo sistema operativo. \n\nSeleziona un'opzione" "il certificato esiste già." "Devo scaricarlo di nuovo?" "Sì" "No" "I seguenti certificati sono stati scaricati e installati:" "Deve essere root... Uscita..." "manca sparky-xterm... Uscita..." "Tutti i certificati radice ICP-Brasil"
create_lang_file "ja" "名前" "説明" "終了" "証明書インストーラー" "オペレーティングシステム内にCA証明書をインストールします。 \n\nオプションを選択してください" "証明書はすでに存在します。" "再ダウンロードしますか？" "はい" "いいえ" "次の証明書がダウンロードされ、インストールされました：" "rootである必要があります...終了しています..." "sparky-xtermがありません...終了しています..." "すべてのICP-Brasilルート証明書"
create_lang_file "ka" "სახელი" "აღწერა" "გასვლა" "სერთიფიკატის ინსტალერი" "ის აყენებს CA სერთიფიკატებს თქვენს ოპერაციულ სისტემაში. \n\nგთხოვთ, აირჩიოთ ვარიანტი" "სერთიფიკატი უკვე არსებობს." "ხელახლა უნდა გადმოვწერო?" "დიახ" "არა" "შემდეგი სერთიფიკატები გადმოწერილი და დაინსტალირებულია:" "უნდა იყოს root... გასვლა..." "აკლია sparky-xterm... გასვლა..." "ყველა ICP-Brasil ძირეული სერთიფიკატი"
create_lang_file "kab" "Isem" "Aglam" "Ffeɣ" "Aseɣẓan n tistam" "Aseɣẓan n tistam n CA deg unagraw n umseɣli-nwen. \n\nFren yiwet n teɣzert" "tistam-nni tella yakan." "Ad tt-id-ssudreɣ tikkelt nniḍen?" "Ih" "Ala" "Tistam-agi i d-iteddun ssudren-tt-id yerna sseɣẓen-tt:" "Ilaq ad telliḍ d root... Tuffɣa..." "ileqqem sparky-xterm... Tuffɣa..." "Akk tistam n uẓar n ICP-Brasil"
create_lang_file "kk" "Аты" "Сипаттама" "Шығу" "Сертификат орнатушы" "Ол операциялық жүйеңізде CA сертификаттарын орнатады. \n\nОпцияны таңдаңыз" "сертификат бұрыннан бар." "Оны қайта жүктеп алуым керек пе?" "Иә" "Жоқ" "Келесі сертификаттар жүктеп алынып, орнатылды:" "Root болуы керек... Шығу..." "sparky-xterm жоқ... Шығу..." "Барлық ICP-Brasil түбірлік сертификаттары"
create_lang_file "km" "ឈ្មោះ" "ការពិពណ៌នា" "ចេញ" "កម្មវិធីដំឡើងវិញ្ញាបនបត្រ" "វាដំឡើងវិញ្ញាបនបត្រ CA នៅខាងក្នុងប្រព័ន្ធប្រតិបត្តិការរបស់អ្នក។ \n\nសូមជ្រើសរើសជម្រើស" "វិញ្ញាបនបត្រមានរួចហើយ។" "តើខ្ញុំគួរទាញយកវាម្តងទៀតទេ?" "បាទ" "ទេ" "វិញ្ញាបនបត្រខាងក្រោមត្រូវបានទាញយក និងដំឡើងរួចហើយ៖" "ត្រូវតែជា root... កំពុងចេញ..." "sparky-xterm បាត់... កំពុងចេញ..." "វិញ្ញាបនបត្រឫស ICP-Brasil ទាំងអស់"
create_lang_file "kn" "ಹೆಸರು" "ವಿವರಣೆ" "ನಿರ್ಗಮಿಸು" "ಪ್ರಮಾಣಪತ್ರ ಸ್ಥಾಪಕ" "ಇದು ನಿಮ್ಮ ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಂನಲ್ಲಿ CA ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಸ್ಥಾಪಿಸುತ್ತದೆ. \n\nದಯವಿಟ್ಟು ಒಂದು ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ" "ಪ್ರಮಾಣಪತ್ರ ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ." "ನಾನು ಅದನ್ನು ಮರು-ಡೌನ್‌ಲೋಡ್ ಮಾಡಬೇಕೇ?" "ಹೌದು" "ಇಲ್ಲ" "ಕೆಳಗಿನ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಸ್ಥಾಪಿಸಲಾಗಿದೆ:" "ರೂಟ್ ಆಗಿರಬೇಕು... ನಿರ್ಗಮಿಸಲಾಗುತ್ತಿದೆ..." "sparky-xterm ಕಾಣೆಯಾಗಿದೆ... ನಿರ್ಗಮಿಸಲಾಗುತ್ತಿದೆ..." "ಎಲ್ಲಾ ICP-ಬ್ರೆಜಿಲ್ ಮೂಲ ಪ್ರಮಾಣಪತ್ರಗಳು"
create_lang_file "ko" "이름" "설명" "종료" "인증서 설치 프로그램" "운영 체제 내에 CA 인증서를 설치합니다. \n\n옵션을 선택하십시오" "인증서가 이미 있습니다." "다시 다운로드해야 합니까?" "예" "아니요" "다음 인증서가 다운로드되어 설치되었습니다." "루트여야 합니다... 종료 중..." "sparky-xterm이 없습니다... 종료 중..." "모든 ICP-Brasil 루트 인증서"
create_lang_file "ku" "Nav" "Danasîn" "Derketin" "Sazkerê Sertîfîkayê" "Ew sertîfîkayên CA di nav pergala xebitandina we de saz dike. \n\nJi kerema xwe vebijarkek hilbijêrin" "sertîfîka jixwe heye." "Divê ez wê ji nû ve dakêşim?" "Erê" "Na" "Sertîfîkayên jêrîn hatine daxistin û sazkirin:" "Divê root be... Derketin..." "sparky-xterm kêm e... Derketin..." "Hemî sertîfîkayên root ên ICP-Brasil"
create_lang_file "lo" "ຊື່" "ລາຍລະອຽດ" "ອອກ" "ຕົວຕິດຕັ້ງໃບຢັ້ງຢືນ" "ມັນຕິດຕັ້ງໃບຢັ້ງຢືນ CA ພາຍໃນລະບົບປະຕິບັດການຂອງທ່ານ. \n\nກະລຸນາເລືອກຕົວເລືອກ" "ໃບຢັ້ງຢືນມີຢູ່ແລ້ວ." "ຂ້ອຍຄວນດາວໂຫລດມັນຄືນໃໝ່ບໍ?" "ແມ່ນ" "ບໍ່" "ໃບຢັ້ງຢืนຕໍ່ໄປນີ້ໄດ້ຖືກດາວໂຫຼດ ແລະຕິດຕັ້ງແລ້ວ:" "ຕ້ອງເປັນ root... ກຳລັງອອກ..." "sparky-xterm ຫາຍ... ກຳລັງອອກ..." "ໃບຢັ້ງຢືນຮາກ ICP-Brasil ທັງໝົດ"
create_lang_file "lt" "Pavadinimas" "Aprašymas" "Išeiti" "Sertifikatų diegimo programa" "Ji įdiegia CA sertifikatus jūsų operacinėje sistemoje. \n\nPasirinkite parinktį" "sertifikatas jau yra." "Ar turėčiau jį atsisiųsti iš naujo?" "Taip" "Ne" "Šie sertifikatai buvo atsiųsti ir įdiegti:" "Turi būti root... Išeinama..." "trūksta sparky-xterm... Išeinama..." "Visi ICP-Brasil šakniniai sertifikatai"
create_lang_file "lv" "Nosaukums" "Apraksts" "Iziet" "Sertifikātu instalētājs" "Tas instalē CA sertifikātus jūsu operētājsistēmā. \n\nLūdzu, atlasiet opciju" "sertifikāts jau pastāv." "Vai man to vajadzētu lejupielādēt vēlreiz?" "Jā" "Nē" "Ir lejupielādēti un instalēti šādi sertifikāti:" "Jābūt root... Iziet..." "trūkst sparky-xterm... Iziet..." "Visi ICP-Brasil saknes sertifikāti"
create_lang_file "mk" "Име" "Опис" "Излез" "Инсталатор на сертификати" "Инсталира CA сертификати во вашиот оперативен систем. \n\nВе молиме изберете опција" "сертификатот веќе постои." "Дали треба повторно да го преземам?" "Да" "Не" "Следниве сертификати се преземени и инсталирани:" "Мора да биде root... Излегување..." "недостасува sparky-xterm... Излегување..." "Сите коренски сертификати на ICP-Brasil"
create_lang_file "ml" "പേര്" "വിവരണം" "പുറത്തുകടക്കുക" "സർട്ടിഫിക്കറ്റ് ഇൻസ്റ്റാളർ" "ഇത് നിങ്ങളുടെ ഓപ്പറേറ്റിംഗ് സിസ്റ്റത്തിനുള്ളിൽ CA സർട്ടിഫിക്കറ്റുകൾ ഇൻസ്റ്റാൾ ചെയ്യുന്നു. \n\nദയവായി ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക" "സർട്ടിഫിക്കറ്റ് ഇതിനകം നിലവിലുണ്ട്." "ഞാൻ അത് വീണ്ടും ഡൗൺലോഡ് ചെയ്യണോ?" "അതെ" "ഇല്ല" "ഇനിപ്പറയുന്ന സർട്ടിഫിക്കറ്റുകൾ ഡൗൺലോഡ് ചെയ്ത് ഇൻസ്റ്റാൾ ചെയ്തിട്ടുണ്ട്:" "റൂട്ട് ആയിരിക്കണം... പുറത്തുകടക്കുന്നു..." "sparky-xterm കാണുന്നില്ല... പുറത്തുകടക്കുന്നു..." "എല്ലാ ICP-ബ്രസീൽ റൂട്ട് സർട്ടിഫിക്കറ്റുകളും"
create_lang_file "mr" "नाव" "वर्णन" "बाहेर पडा" "प्रमाणपत्र इंस्टॉलर" "हे तुमच्या ऑपरेटिंग सिस्टममध्ये CA प्रमाणपत्रे स्थापित करते. \n\nकृपया एक पर्याय निवडा" "प्रमाणपत्र आधीच अस्तित्वात आहे." "मी ते पुन्हा डाउनलोड करावे का?" "होय" "नाही" "खालील प्रमाणपत्रे डाउनलोड आणि स्थापित केली आहेत:" "रूट असणे आवश्यक आहे... बाहेर पडत आहे..." "sparky-xterm गहाळ आहे... बाहेर पडत आहे..." "सर्व ICP-ब्राझील मूळ प्रमाणपत्रे"
create_lang_file "nl" "Naam" "Omschrijving" "Afsluiten" "Certificaatinstallatieprogramma" "Installeert CA-certificaten in uw besturingssysteem. \n\nSelecteer een optie" "certificaat bestaat al." "Moet ik het opnieuw downloaden?" "Ja" "Nee" "De volgende certificaten zijn gedownload en geïnstalleerd:" "Moet root zijn... Afsluiten..." "sparky-xterm ontbreekt... Afsluiten..." "Alle ICP-Brasil-basiscertificaten"
create_lang_file "nn" "Namn" "Skildring" "Avslutt" "Sertifikatinstallerar" "Installerer CA-sertifikat i operativsystemet ditt. \n\nVel eit alternativ" "sertifikatet finst allereie." "Skal eg lasta det ned på nytt?" "Ja" "Nei" "Følgjande sertifikat er lasta ned og installert:" "Må vera root ... Avsluttar ..." "sparky-xterm manglar ... Avsluttar ..." "Alle ICP-Brasil-rotsertifikat"
create_lang_file "oc" "Nom" "Descripcion" "Quitar" "Installador de certificats" "Installa los certificats de l'AC dins vòstre sistèma d'explotacion. \n\nSeleccionatz una opcion" "lo certificat existís ja." "Lo devi telecargar tornarmai ?" "Òc" "Non" "Los certificats seguents son estats telecargats e installats :" "Deu èsser root... Sortida..." "sparky-xterm es mancant... Sortida..." "Totes los certificats racines d'ICP-Brasil"
create_lang_file "pa" "ਨਾਮ" "ਵੇਰਵਾ" "ਬਾਹਰ" "ਸਰਟੀਫਿਕੇਟ ਇੰਸਟਾਲਰ" "ਇਹ ਤੁਹਾਡੇ ਓਪਰੇਟਿੰਗ ਸਿਸਟਮ ਦੇ ਅੰਦਰ CA ਸਰਟੀਫਿਕੇਟ ਇੰਸਟਾਲ ਕਰਦਾ ਹੈ। \n\nਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵਿਕਲਪ ਚੁਣੋ" "ਸਰਟੀਫਿਕੇਟ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ।" "ਕੀ ਮੈਨੂੰ ਇਸਨੂੰ ਦੁਬਾਰਾ ਡਾਊਨਲੋਡ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ?" "ਹਾਂ" "ਨਹੀਂ" "ਹੇਠਾਂ ਦਿੱਤੇ ਸਰਟੀਫਿਕੇਟ ਡਾਊਨਲੋਡ ਅਤੇ ਇੰਸਟਾਲ ਕੀਤੇ ਗਏ ਹਨ:" "ਰੂਟ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ... ਬਾਹर ਆ ਰਿਹਾ ਹੈ..." "sparky-xterm ਗੁੰਮ ਹੈ... ਬਾਹਰ ਆ ਰਿਹਾ ਹੈ..." "ਸਾਰੇ ICP-ਬ੍ਰਾਜ਼ੀਲ ਰੂਟ ਸਰਟੀਫਿਕੇਟ"
create_lang_file "pl" "Nazwa" "Opis" "Wyjdź" "Instalator certyfikatów" "Instaluje certyfikaty CA w twoim systemie operacyjnym. \n\nWybierz opcję" "certyfikat już istnieje." "Czy mam go pobrać ponownie?" "Tak" "Nie" "Pobrano i zainstalowano następujące certyfikaty:" "Musi być root... Zamykanie..." "brakuje sparky-xterm... Zamykanie..." "Wszystkie certyfikaty główne ICP-Brasil"
create_lang_file "pt" "Nome" "Descrição" "Sair" "Instalador de Certificados" "Instala certificados de CA no seu sistema operativo. \n\nSelecione uma opção" "o certificado já existe." "Devo transferi-lo novamente?" "Sim" "Não" "Os seguintes certificados foram transferidos e instalados:" "Tem de ser root... A sair..." "falta o sparky-xterm... A sair..." "Todos os certificados de raiz do ICP-Brasil"
create_lang_file "ro" "Nume" "Descriere" "Ieșire" "Instalator de certificate" "Instalează certificate CA în sistemul dumneavoastră de operare. \n\nVă rugăm să selectați o opțiune" "certificatul există deja." "Ar trebui să-l descarc din nou?" "Da" "Nu" "Următoarele certificate au fost descărcate și instalate:" "Trebuie să fiți root... Ieșire..." "lipsește sparky-xterm... Ieșire..." "Toate certificatele rădăcină ICP-Brasil"
create_lang_file "ru" "Имя" "Описание" "Выход" "Установщик сертификатов" "Устанавливает сертификаты CA в вашей операционной системе. \n\nПожалуйста, выберите опцию" "сертификат уже существует." "Следует ли мне загрузить его снова?" "Да" "Нет" "Следующие сертификаты были загружены и установлены:" "Должен быть root... Выход..." "отсутствует sparky-xterm... Выход..." "Все корневые сертификаты ICP-Brasil"
create_lang_file "si" "නම" "විස්තරය" "පිටවීම" "සහතික ස්ථාපකය" "එය ඔබගේ මෙහෙයුම් පද්ධතිය තුළ CA සහතික ස්ථාපනය කරයි. \n\nකරුණාකර විකල්පයක් තෝරන්න" "සහතිකය දැනටමත් පවතී." "මම එය නැවත බාගත යුතුද?" "ඔව්" "නැත" "පහත සහතික බාගත කර ස්ථාපනය කර ඇත:" "root විය යුතුය... පිටවುತ್ತಿದೆ..." "sparky-xterm חסר... පිටවುತ್ತಿದೆ..." "සියලුම ICP-Brasil මූල සහතික"
create_lang_file "sk" "Názov" "Popis" "Koniec" "Inštalátor certifikátov" "Nainštaluje certifikáty CA do vášho operačného systému. \n\nVyberte si možnosť" "certifikát už existuje." "Mám ho stiahnuť znova?" "Áno" "Nie" "Nasledujúce certifikáty boli stiahnuté a nainštalované:" "Musí byť root... Končím..." "chýba sparky-xterm... Končím..." "Všetky koreňové certifikáty ICP-Brasil"
create_lang_file "sl" "Ime" "Opis" "Izhod" "Namestitveni program za potrdila" "Namesti potrdila CA v vaš operacijski sistem. \n\nIzberite možnost" "potrdilo že obstaja." "Ali naj ga ponovno prenesem?" "Da" "Ne" "Naslednja potrdila so bila prenesena in nameščena:" "Mora biti root... Izhod..." "manjka sparky-xterm... Izhod..." "Vsa korenska potrdila ICP-Brasil"
create_lang_file "sr" "Име" "Опис" "Излаз" "Инсталатер сертификата" "Инсталира ЦА сертификате унутар вашег оперативног система. \n\nМолимо изаберите опцију" "сертификат већ постоји." "Да ли да га поново преузмем?" "Да" "Не" "Следећи сертификати су преузети и инсталирани:" "Мора бити роот... Излазим..." "недостаје спарки-кстерм... Излазим..." "Сви ИЦП-Брасил корени сертификати"
create_lang_file "sv" "Namn" "Beskrivning" "Avsluta" "Certifikatinstallerare" "Det installerar CA-certifikat i ditt operativsystem. \n\nVälj ett alternativ" "certifikatet finns redan." "Ska jag ladda ner det igen?" "Ja" "Nej" "Följande certifikat har laddats ner och installerats:" "Måste vara root... Avslutar..." "sparky-xterm saknas... Avslutar..." "Alla ICP-Brasil-rotcertifikat"
create_lang_file "ta" "பெயர்" "விளக்கம்" "வெளியேறு" "சான்றிதழ் நிறுவி" "இது உங்கள் இயக்க முறைமையில் CA சான்றிதழ்களை நிறுவுகிறது. \n\nஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்" "சான்றிதழ் ஏற்கனவே உள்ளது." "நான் அதை மீண்டும் பதிவிறக்க வேண்டுமா?" "ஆம்" "இல்லை" "பின்வரும் சான்றிதழ்கள் பதிவிறக்கம் செய்யப்பட்டு நிறுவப்பட்டுள்ளன:" "ரூட்டாக இருக்க வேண்டும்... வெளியேறுகிறது..." "sparky-xterm காணவில்லை... வெளியேறுகிறது..." "அனைத்து ICP-பிரேசில் ரூட் சான்றிதழ்கள்"
create_lang_file "te" "పేరు" "వివరణ" "నిష్క్రమించు" "సర్టిఫికేట్ ఇన్‌స్టాలర్" "ఇది మీ ఆపరేటింగ్ సిస్టమ్‌లో CA సర్టిఫికేట్‌లను ఇన్‌స్టాల్ చేస్తుంది. \n\nదయచేసి ఒక ఎంపికను ఎంచుకోండి" "సర్టిఫికేట్ ఇప్పటికే ఉంది." "నేను దాన్ని మళ్లీ డౌన్‌లోడ్ చేయాలా?" "అవును" "కాదు" "కింది సర్టిఫికేట్‌లు డౌన్‌లోడ్ చేయబడి, ఇన్‌స్టాల్ చేయబడ్డాయి:" "రూట్ అయి ఉండాలి... నిష్క్రమిస్తోంది..." "sparky-xterm కనబడలేదు... నిష్క్రమిస్తోంది..." "అన్ని ICP-బ్రెజిల్ రూట్ సర్టిఫికేట్‌లు"
create_lang_file "th" "ชื่อ" "คำอธิบาย" "ออก" "โปรแกรมติดตั้งใบรับรอง" "ติดตั้งใบรับรอง CA ภายในระบบปฏิบัติการของคุณ \n\nโปรดเลือกตัวเลือก" "มีใบรับรองอยู่แล้ว" "ฉันควรดาวน์โหลดอีกครั้งหรือไม่" "ใช่" "ไม่" "ดาวน์โหลดและติดตั้งใบรับรองต่อไปนี้แล้ว:" "ต้องเป็นรูท... กำลังออก..." "ไม่มี sparky-xterm... กำลังออก..." "ใบรับรองหลักของ ICP-Brasil ทั้งหมด"
create_lang_file "tr" "Ad" "Açıklama" "Çıkış" "Sertifika Yükleyici" "İşletim sisteminize CA sertifikalarını yükler. \n\nLütfen bir seçenek seçin" "sertifika zaten var." "Tekrar indirmeli miyim?" "Evet" "Hayır" "Aşağıdaki sertifikalar indirilip yüklendi:" "Root olmalı... Çıkılıyor..." "sparky-xterm eksik... Çıkılıyor..." "Tüm ICP-Brasil kök sertifikaları"
create_lang_file "uk" "Ім'я" "Опис" "Вихід" "Інсталятор сертифікатів" "Встановлює сертифікати CA у вашій операційній системі. \n\nБудь ласка, виберіть опцію" "сертифікат вже існує." "Чи варто мені його завантажити знову?" "Так" "Ні" "Наступні сертифікати були завантажені та встановлені:" "Повинен бути root... Вихід..." "відсутній sparky-xterm... Вихід..." "Усі кореневі сертифікати ICP-Brasil"
create_lang_file "vi" "Tên" "Mô tả" "Thoát" "Trình cài đặt chứng chỉ" "Nó cài đặt chứng chỉ CA bên trong hệ điều hành của bạn. \n\nVui lòng chọn một tùy chọn" "chứng chỉ đã tồn tại." "Tôi có nên tải xuống lại không?" "Có" "Không" "Các chứng chỉ sau đã được tải xuống và cài đặt:" "Phải là root... Đang thoát..." "thiếu sparky-xterm... Đang thoát..." "Tất cả các chứng chỉ gốc của ICP-Brasil"
create_lang_file "zh_CN" "名称" "描述" "退出" "证书安装程序" "它会在您的操作系统内安装 CA 证书。 \n\n请选择一个选项" "证书已存在。" "我应该重新下载吗？" "是" "否" "以下证书已下载并安装：" "必须是 root... 正在退出..." "缺少 sparky-xterm... 正在退出..." "所有 ICP-Brasil 根证书"
create_lang_file "zh_TW" "名稱" "描述" "離開" "憑證安裝程式" "它會在您的作業系統內安裝 CA 憑證。 \n\n請選擇一個選項" "憑證已存在。" "我應該重新下載嗎？" "是" "否" "以下憑證已下載並安裝：" "必須是 root... 正在離開..." "缺少 sparky-xterm... 正在離開..." "所有 ICP-Brasil 根憑證"
